# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 01acc9cb5a511831b2744f292ac9f23cff10f438218b67080d18e8ab31343ae394a4605683d0e88ee1e7434ffbef87bedbb3f9dbbe107c9c58a98d58c37b1e5f

test:
  secret_key_base: 456853def6fe432681f70995d577b83854edd6d042d1ff8a24be6eef78aa317e2b9ebc01647306309990587afeaab5f2e8cb4c18b04e13cf51e8c2cdcd8bfaa9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
